### PR TITLE
Update debian instruction to respect actul debian guidelines.

### PR DESCRIPTION
**Pull request by 532910**
https://manpages.debian.org/stretch/apt/apt-key.8.en.html
https://wiki.debian.org/DebianRepository/UseThirdParty

### CODE REVIEW

**Comment by calmh** [comment]
This doesn't work on my Ubuntu. Specifically it looks like the key requires dearmoring;

https://wiki.debian.org/DebianRepository/UseThirdParty

**Comment by 532910** [comment]
> Ubuntu

version?

**Comment by calmh** [comment]
16.04, but it does work after dearmoring like that article suggest

**Comment by 532910** [comment]
Are you sure? As it doesn't work for me even after dearmoring. (in debootstrap's xenial chroot)

**Comment by calmh** [comment]
Well I'm not going to argue with it not working for you. :)

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
