### PR TITLE
adds link to syncthing.net on the logo

### PR DESCRIPTION
**Pull request by hennr**

### CODE REVIEW

**Comment by hennr** [comment]
Anyone?

**Comment by calmh** [comment]
Sure!

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as aa0fe6243483d800f6abc7dc97e919f910d21fb5. Thanks, @hennr!

**Comment by hennr** [comment]
Nice, thanks @calmh

**Pull request closed without merging**
