### PR TITLE
List supported architectures and options

### PR DESCRIPTION
**Pull request by Aeyoun**
E.T. link back home.

[Review on Reviewable](https://reviewable.io/reviews/syncthing/apt-web/3)

### CODE REVIEW

**Comment by calmh** [comment]
There are also armel and armhf packages.

**Comment by Aeyoun** [comment]
I could almost swear there were no armhf packages the last time I checked.

**Comment by Aeyoun** [comment]
No, I’m not crazy. There are no armhf packages in the repository.

W: Failed to fetch http://apt.syncthing.net/dists/syncting/release/binary-armhf/Packages  404  Not Found

**Comment by calmh** [comment]
On the contrary, it's there if you spell "syncthing" correctly. ;)

**Pull request merged**
