### PR TITLE
Replace deprecated use of apt-key

### LINKED ISSUE #6: provide the OpenPGP trust anchor as a binary file
The [Debian/Ubuntu install instructions](http://apt.syncthing.net/) indicate we should run:

```
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
```

While this is good, it's not considered best practice. Apart from verifying the key (which should be done separately, and is a whole different set of problems), the key should not be added to the global trust anchor in `/etc/apt/trusted.gpg` (which `apt-key add -` does). This makes it more difficult to track which package added which key, as this file can grow big and unmaintained.

A better way would be:

```
sudo wget -O /etc/apt/trusted.gpg.d/syncthing.gpg https://syncthing.net/release-key.gpg
```

It involves less commandline knowledge (no pipeline), is a single command, and will make the OpenPGP certificate end up in a separate file, distinct from all the others.

This is how Ubuntu PPAs manage their keys as well, and is considered a better practice than piping stuff through `apt-key`.

Note how the file name change: the `.gpg` file is _not_ an ascii-armored file (as produced by `gpg --export --armor`) but a binary OpenPGP file. This is also expected (and will _break_ APT if used with the `txt` file).

Ideally, there would be a PPA for Syncthing or it would just enter Debian already, but works still seems to be underway there (see [bug #749887 in the Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749887)).

Note: moved from  https://github.com/syncthing/syncthing/issues/2843

### PR DESCRIPTION
**Pull request by brianclinkenbeard**
See `apt-key` manpages. Fixes #6

### CODE REVIEW

**Comment by acolomb** [comment]
I like the idea in general, but the new command looks quite scary involving `dd` and another pipe indirection.

How about we instead specify a sensible keyring file within `trusted.gpg.d` using the `--keyring` option to `apt-key`?  Then we would not need to worry about armored vs. binary key formats.

       --keyring filename
           With this option it is possible to specify a particular keyring file the command
           should operate on. The default is that a command is executed on the trusted.gpg file
           as well as on all parts in the trusted.gpg.d directory, though trusted.gpg is the
           primary keyring which means that e.g. new keys are added to this one.

**Comment by brianclinkenbeard** [comment]
I agree the use of `dd` looks scary, even though `cat` or `tee` can be just as dangerous if directed to the places we usually use `dd` for (disk operations etc). `tee ... >/dev/null` is another possibility (less scary looking but more verbose).

What you mention is also possible, however `apt-key` and will soon be removed from the next testing releases of Ubuntu/Debian (bullseye freezes in January to prepare for the new release).

The current solution is definitely inelegant, but unfortunately without `apt-key` we are left with no good options for armored keys.

**Comment by acolomb** [comment]
> What you mention is also possible, however `apt-key` and will soon be removed from the next testing releases of Ubuntu/Debian (bullseye freezes in January to prepare for the new release).

Interesting, thanks for pointing this out. (What an asinine move actually, considering how many copy-paste installation instructions will start to fail.)

Can we at least assume `gpg` is and will be available on every Debian system for the foreseeable future? AFAIK what APT needs is only the `gpgv` binary.

I thought about a `tee ... > /dev/null` solution as well, but that's really ugly. Easiest would be to just run `curl` itself through `sudo` and have it write to a file.  Provided the key is made available in non-armored form on the website.  What is Debian's recommendation to (manually) install files in `/etc/apt/trusted.gpg.d/`?

**Comment by brianclinkenbeard** [comment]
>  What is Debian's recommendation to (manually) install files in `/etc/apt/trusted.gpg.d/`?

All it says is "manage keyring files in trusted.gpg.d instead". With a dearmored file `sudo wget -O` or `curl -o` would be an optimal solution.

**Comment by imsodin** [comment]
Meaning if we create and place a dearmored release-key.gpg from the .txt in https://github.com/syncthing/website, you can just use `curl -o` here, right? Then lets do that instead of confusing users with even more pipes and tools.

**Comment by acolomb** [comment]
Agreed, so @imsodin are you looking into making that available? Probably not much machinery required, just a one-time conversion whenever the key expires.

**Comment by calmh** [comment]
I've done that now, there is a release-key.gpg which is binary.

**Comment by acolomb** [comment]
@brianclinkenbeard Would you mind updating the PR to use the dearmored file directly?

**Comment by brianclinkenbeard** [comment]
Don't ask me the reasoning behind this, but it's [been brought to my attention](https://github.com/vector-im/element.io/issues/6#issuecomment-751277578) that the `trusted.gpg.d` is now also deprecated and the new preferred way to store keys is to save them to `/usr/share/keyrings/` and adding a `signed-by` flag to the list file: https://wiki.debian.org/DebianRepository/UseThirdParty

I've made the changes according to the new recommendations.

**Review by calmh — APPROVED** [review]
This seems sound

**Comment by acolomb** [comment]
The APT folks are going haywire. Placing stuff under /usr is a privilege to DEB packages. Administrators should fiddle only with /etc or at the very least /usr/local. That's to be found in Debian's own policy IIRC.

Shipping the key file within the package and installing from there to /usr/share/keyrings would be a sane way to handle that, at least for updates. Some proprietary software goes that route to provide authenticated updates. But Syncthing probably doesn't want to *force* users into having the APT repo enabled. 

The new instructions here at least match Debian's current recommendation, so it should be fine.

**Comment by andrewshadura** [comment]
> The APT folks are going haywire. 

Please refrain from accusing people you disagree with of insanity. Thanks.

> Placing stuff under /usr is a privilege to DEB packages. Administrators should fiddle only with /etc or at the very least /usr/local. That's to be found in Debian's own policy IIRC.

That’s how you’re supposed to ship keyrings, in packages.

If you’re wondering what’s wrong with `trusted.gpg.d`, it’s this: you don’t want e.g. Spotify to ship your bash or Skype to ship your systemd. Even by accident, not malice. While this is currently unenforceable with APT, separating trust can enable that in future. What APT can enforce now by using `signed-by` instead of blind trust, is to disallow signing package lists with other keys, disabling potential replay attacks, when someone can ship old Debian package list referencing a vulnerable version of some package from the main repository.

**Comment by andrewshadura** [comment]
As for /etc vs /usr, `signed-by` uses absolute paths, so those keyrings can be placed anywhere.

**Comment by acolomb** [comment]
Sorry if I used harsh words, no offense intended. I meant to say that the changes seem chaotic, deprecating stuff without clearly documented replacement solutions. There are some partial solutions, but they seem mainly tailored toward package creators, not admins trying to install one specific application. Such as suggesting a user / admin to place key files into /usr/share manually. 

I fully agree with the direction taken to separate trust for repositories. It's been a sore spot for a very long time. Just the path of removing a convenience utility (apt-key) that helps users to stick to the Right Way of doing things is unhelpful. If it can't be fixed, there should at least be clear instructions what admins should do instead. Which should be restricted to modifying /etc as always has been.

**Comment by andrewshadura** [comment]
Well, to be fair, `trusted.d` is not deprecated yet, but the intention is to do that at some point in future, as far as I can see.

I guess these pages can explain the reason for this:
https://wiki.debian.org/DebianRepository/UseThirdParty
https://wiki.debian.org/UntrustedDebs

**Pull request merged**
